linters:
  disable-all: true
  enable:
    - errcheck    # Перевіряє, чи не забув ти обробити помилку
    - gosimple    # Підказує, як спростити код
    - unused      # Шукає змінні чи функції, які ніде не використовуються
    - revive      # Перевіряє стиль коду (заміна застарілого golint)
    - staticcheck # Потужний аналізатор багів